---
title: "Advent of Code 2022 - Day 6"
author: "Sara Berg-Love"
date: "2022-12-6"
output: github_document
---

https://adventofcode.com/2022/day/6

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries
library(tidyverse)

# Load in file
file <- here::here("2022/data/day6")
```

```{r, message = FALSE}
# Save data
data <- read_file(file)
```

```{r}
# While the end of the range (4 total characters) is less than the total string 
# length, subset the string and iterate through to see if there are more than 1 
# of any letter in the string. If not, that is the end of the marker. If there 
# are duplicates, increase the range by one and iterate through again.

start = 1
end = 4
flag = TRUE
letter = letters

while (end <= str_length(data) && flag == TRUE) {
  var_string <- str_sub(data, start = start, end = end)
  i <- 1
  flag <- FALSE
  while (i <= 26 && flag == FALSE) {
    flag <- if_else(str_count(var_string, letter[i]) > 1, TRUE, FALSE)
    i = i + 1
  }
  start = start + 1
  end = end + 1
}

end - 1
```

```{r}
# While the end of the range (14 total characters) is less than the total string 
# length, subset the string and iterate through to see if there are more than 1 
# of any letter in the string. If not, that is the end of the marker. If there 
# are duplicates, increase the range by one and iterate through again.

start = 1
end = 14
flag = TRUE

while (end <= str_length(data) && flag == TRUE) {
  var_string <- str_sub(data, start = start, end = end)
  i <- 1
  flag <- FALSE
  while (i <= 26 && flag == FALSE) {
    flag <- if_else(str_count(var_string, letter[i]) > 1, TRUE, FALSE)
    i = i + 1
  }
  start = start + 1
  end = end + 1
}

end - 1
```
