---
title: "Advent of Code 2022 - Day 3"
author: "Sara Berg-Love"
date: "2022-12-03"
output: github_document
---

https://adventofcode.com/2022/day/3 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries
library(tidyverse)

# Load in file
file <- here::here("2022/data/day3")
```

```{r, message = FALSE}
# Save data
backpacks <- read_table(file, col_names = "backpack")
```

```{r}
# Set up values for different items
#   Lowercase item types a through z have priorities 1 through 26.
#   Uppercase item types A through Z have priorities 27 through 52.
values <- 
  data.frame(letter = c(letters, LETTERS)) %>% 
  mutate(value = row_number())
```

```{r}
# Separate items into 2 compartments based on length
items <- 
  backpacks %>% 
  mutate(
    size = str_length(backpack),
    compartment1 = str_sub(backpack, start = 1, end = size / 2),
    compartment2 = str_sub(backpack, start = size / 2 + 1, end = -1)
    )
```


```{r}
# Function to extract matching character in 2 strings
match_string <- function(str1, str2) {
  str3 <- str_glue("[", str2, "]")
  return(str_extract(str1, str3))
}
```


```{r}
# Map character matching function to items in both compartments and combine 
# values table with matching item
items <- 
  items %>% 
  mutate(
    letter = map2_chr(compartment1, compartment2, ~match_string(.x, .y))
  ) %>% 
  left_join(values, by = "letter")
```


```{r}
# Find sum of item priorities
items %>% 
  summarize(sum(value))
```

```{r}
# Iterate through list of backpack items separating elves into groups of 3

badges <- 
  backpacks %>% 
  mutate(group = NA, elf = NA)

i <- 1
j <- 0

while(i < nrow(badges) + 1) {
  if(i %% 3 == 1){
    j = j + 1
  }
  badges[i, "group"] <- j
  badges[i, "elf"] <- str_glue("elf", as.character(i %% 3 + 1))
  i = i + 1
}
```

```{r}
# Pivot table wider to group the elves into rows
badges <- 
  badges %>% 
  pivot_wider(id_cols = group, names_from = "elf", values_from = "backpack")
```

```{r}
# Function to extract all matching characters in 2 strings
match_string_2 <- function(str1, str2) {
  str3 <- str_glue("[", str2, "]")
  return(str_c(as_vector(str_extract_all(str1, str3)), collapse = ""))
}
```

```{r}
# Map character matching function to items carried by first two elves to get 
# list of common items to both of them. Then map that common list to the third
# elf. Then combine values table with matching badge item.
badges <- 
  badges %>% 
  mutate(
    matches = map2_chr(elf1, elf2, ~match_string_2(.x, .y)),
    letter = map2_chr(matches, elf3, ~match_string(.x, .y))
  ) %>% 
  left_join(values, by = "letter")
```


```{r}
# Find sum of badge item priorities
badges %>% 
  summarize(sum(value))
```
  
